# @package _group_

# don't forget loggers.login() for the first usage.

log: True  # set to False to avoid the logging

wandb_arg:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: model_name
  log_model: True

watch:
  log: 'all'
  log_freq: 100